name: Random Commit
on: 
  workflow_dispatch:

jobs:
  random_commit:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          
      - name: Install dependencies
        run: yarn
      
      - name: Run scripts
        run: yarn dev

      - name: Commit changes
        run: |
          git config --local user.email "3038094028@qq.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "chore: sync"
          
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PUSH_TOKEN }}
          branch: ${{ github.ref }}

      
